Repository DEFRA/flood-risk-engine, pull requests merged in 2019-06, with the labels that each got.

#259 Fix Travis CI build
  .travis.yml
  Gemfile.lock
Labels: fix, housekeeping

#258 Update privacy policy
  app/assets/stylesheets/flood_risk_engine/application.css
  app/assets/stylesheets/flood_risk_engine/partials/_published_date.scss
  app/views/pages/privacy_policy.html.erb
  config/locales/pages/privacy_policy.en.yml
  spec/controllers/flood_risk_engine/enrollments/pages_controller_spec.rb
Labels: feature

#260 Update dependencies
  Gemfile.lock
  README.md
  flood_risk_engine.gemspec
  lib/flood_risk_engine/engine.rb
Labels: housekeeping

#262 Fix bulleted list class name
  app/views/pages/privacy_policy.html.erb
Labels: fix

#261 Rename application.css to .scss
  app/assets/stylesheets/flood_risk_engine/application.scss
Labels: fix

#279 Remove duplicate paragraphs from privacy policy
  app/views/pages/privacy_policy.html.erb
Labels: fix

#281 Add github changelog generator to the project
  CHANGELOG.md
  Gemfile.lock
  flood_risk_engine.gemspec
  lib/tasks/changelog.rake
Labels: housekeeping

#282 Update privacy policy date to release date
  app/views/pages/privacy_policy.html.erb
Labels: housekeeping
