Repository DEFRA/flood-risk-engine, pull requests merged in 2019-09, with the labels that each got.

#297 Update water mgmt area job to report errors
  app/jobs/flood_risk_engine/update_water_management_area_job.rb
Labels: enhancement

#298 Fix error in airbrake notification in area lookup
  app/jobs/flood_risk_engine/update_water_management_area_job.rb
  spec/jobs/flood_risk_engine/update_water_management_area_spec.rb
Labels: bug

#299 Add scopes for finding location for area lookup
  app/models/flood_risk_engine/location.rb
  spec/factories/water_management_area_factory.rb
  spec/models/flood_risk_engine/location_spec.rb
Labels: enhancement

#300 Rename scope and parameter in area lookup job
  app/jobs/flood_risk_engine/update_water_management_area_job.rb
  app/models/flood_risk_engine/location.rb
  spec/models/flood_risk_engine/location_spec.rb
Labels: housekeeping

#301 Add scope on location from site addresses
  app/models/flood_risk_engine/location.rb
  spec/factories/addresses_factory.rb
  spec/models/flood_risk_engine/location_spec.rb
Labels: enhancement
