Repository DEFRA/flood-risk-engine, pull requests merged in 2021-09, with the labels that each got.

#415 Fix content and formatting errors on new registration forms
  app/forms/flood_risk_engine/check_your_answers_form.rb
  app/models/concerns/flood_risk_engine/can_have_registration_attributes.rb
  app/presenters/flood_risk_engine/check_your_answers_presenter.rb
  app/views/flood_risk_engine/additional_contact_email_forms/new.html.erb
  app/views/flood_risk_engine/business_type_forms/new.html.erb
  app/views/flood_risk_engine/check_your_answers_forms/new.html.erb
  app/views/flood_risk_engine/company_name_forms/new.html.erb
  app/views/flood_risk_engine/company_number_forms/new.html.erb
  app/views/flood_risk_engine/confirm_exemption_forms/new.html.erb
  app/views/flood_risk_engine/contact_email_forms/new.html.erb
  app/views/flood_risk_engine/contact_name_forms/new.html.erb
  app/views/flood_risk_engine/contact_phone_forms/new.html.erb
  app/views/flood_risk_engine/shared/_error_summary.html.erb
  app/views/flood_risk_engine/site_grid_reference_forms/new.html.erb
  config/locales/flood_risk_engine/business_type_forms.en.yml
  config/locales/flood_risk_engine/check_your_answers_forms.en.yml
  config/locales/flood_risk_engine/company_name_forms.en.yml
  config/locales/flood_risk_engine/company_number_forms.en.yml
  config/locales/flood_risk_engine/confirm_exemption_forms.en.yml
  config/locales/flood_risk_engine/contact_email_forms.en.yml
  config/locales/flood_risk_engine/contact_name_forms.en.yml
  config/locales/flood_risk_engine/contact_phone_forms.en.yml
  config/locales/flood_risk_engine/exemption_forms.en.yml
  config/locales/flood_risk_engine/partner_address_lookup_forms.en.yml
  config/locales/flood_risk_engine/partner_address_manual_forms.en.yml
  config/locales/flood_risk_engine/partner_name_forms.en.yml
  config/locales/flood_risk_engine/partner_overview_forms.en.yml
  config/locales/flood_risk_engine/partner_postcode_forms.en.yml
  config/locales/flood_risk_engine/site_grid_reference_forms.en.yml
  spec/factories/new_registrations_factory.rb
  spec/presenters/flood_risk_engine/check_your_answers_presenter_spec.rb
Labels: enhancement

#416 Add id to ref number on complete page
  app/views/flood_risk_engine/registration_complete_forms/new.html.erb
Labels: enhancement

#417 Turn NewRegistrations into Enrollments on submission
  app/controllers/flood_risk_engine/registration_complete_forms_controller.rb
  app/forms/flood_risk_engine/registration_complete_form.rb
  app/models/flood_risk_engine/transient_registration.rb
  app/services/flood_risk_engine/registration_completion_service.rb
  app/views/flood_risk_engine/registration_complete_forms/new.html.erb
  spec/factories/new_registrations_factory.rb
  spec/requests/flood_risk_engine/registration_complete_forms_spec.rb
  spec/services/flood_risk_engine/registration_completion_service_spec.rb
Labels: enhancement

#419 Remove TabularEnrollmentDetailPresenters
  app/mailers/flood_risk_engine/enrollment_mailer.rb
  app/presenters/flood_risk_engine/tabular_enrollment_detail/row.rb
  app/presenters/flood_risk_engine/tabular_enrollment_detail/row_builder.rb
  app/presenters/flood_risk_engine/tabular_enrollment_detail_presenter.rb
  spec/presenters/flood_risk_engine/tabular_enrollment_detail_presenter_spec.rb
Labels: housekeeping

#420 Change H3s to H2s on start page
  app/views/flood_risk_engine/start_forms/new.html.erb
Labels: bug

#421 Fix exemption form issues
  app/presenters/flood_risk_engine/exemption_presenter.rb
  app/views/flood_risk_engine/confirm_exemption_forms/new.html.erb
  app/views/flood_risk_engine/exemption_forms/new.html.erb
  config/locales/flood_risk_engine/exemption_forms.en.yml
Labels: bug

#422 Don't display metres twice in hint text
  app/views/flood_risk_engine/site_grid_reference_forms/new.html.erb
Labels: bug

#423 Fix issues on company details pages
  app/views/flood_risk_engine/business_type_forms/new.html.erb
  app/views/flood_risk_engine/company_address_manual_forms/new.html.erb
  app/views/flood_risk_engine/company_postcode_forms/new.html.erb
  app/views/flood_risk_engine/partner_address_manual_forms/new.html.erb
  app/views/flood_risk_engine/partner_postcode_forms/new.html.erb
  app/views/flood_risk_engine/shared/_manual_address.html.erb
  config/locales/flood_risk_engine/partner_postcode_forms.en.yml
Labels: bug

#424 Fix issues on check your answers and end pages
  app/views/flood_risk_engine/declaration_forms/new.html.erb
  app/views/pages/privacy_policy.html.erb
  config/locales/flood_risk_engine/check_your_answers_forms.en.yml
Labels: bug

#426 Add page-specific titles
  app/helpers/flood_risk_engine/application_helper.rb
  app/views/flood_risk_engine/partner_overview_forms/new.html.erb
  app/views/flood_risk_engine/partner_postcode_forms/new.html.erb
  app/views/flood_risk_engine/registration_complete_forms/new.html.erb
  app/views/flood_risk_engine/shared/_os_terms_footer.html.erb
  app/views/flood_risk_engine/site_grid_reference_forms/new.html.erb
  app/views/flood_risk_engine/start_forms/new.html.erb
  config/locales/flood_risk_engine/additional_contact_email_forms.en.yml
  config/locales/flood_risk_engine/business_type_forms.en.yml
  config/locales/flood_risk_engine/check_your_answers_forms.en.yml
  config/locales/flood_risk_engine/company_address_lookup_forms.en.yml
  config/locales/flood_risk_engine/company_address_manual_forms.en.yml
  config/locales/flood_risk_engine/company_name_forms.en.yml
  config/locales/flood_risk_engine/company_number_forms.en.yml
  config/locales/flood_risk_engine/company_postcode_forms.en.yml
  config/locales/flood_risk_engine/confirm_exemption_forms.en.yml
  config/locales/flood_risk_engine/contact_email_forms.en.yml
  config/locales/flood_risk_engine/contact_name_forms.en.yml
  config/locales/flood_risk_engine/contact_phone_forms.en.yml
  config/locales/flood_risk_engine/declaration_forms.en.yml
  config/locales/flood_risk_engine/exemption_forms.en.yml
  config/locales/flood_risk_engine/partner_address_lookup_forms.en.yml
  config/locales/flood_risk_engine/partner_address_manual_forms.en.yml
  config/locales/flood_risk_engine/partner_name_forms.en.yml
  config/locales/flood_risk_engine/partner_overview_forms.en.yml
  config/locales/flood_risk_engine/partner_postcode_forms.en.yml
  config/locales/flood_risk_engine/registration_complete_forms.en.yml
  config/locales/flood_risk_engine/site_grid_reference_forms.en.yml
  spec/helpers/application_helper_spec.rb
Labels: bug

#431 Fix accidental duplicated titles
  app/views/flood_risk_engine/partner_overview_forms/new.html.erb
  app/views/flood_risk_engine/partner_postcode_forms/new.html.erb
  app/views/flood_risk_engine/site_grid_reference_forms/new.html.erb
Labels: bug

#430 Fix missing address org bug for partners
  app/services/flood_risk_engine/registration_completion_service.rb
  spec/services/flood_risk_engine/registration_completion_service_spec.rb
Labels: bug

#429 Fix dredging validation error text
  app/forms/flood_risk_engine/site_grid_reference_form.rb
Labels: bug

#428 Display missing contact position hint
  app/views/flood_risk_engine/contact_name_forms/new.html.erb
  config/locales/flood_risk_engine/contact_name_forms.en.yml
Labels: bug

#432 Don't append extra 0s to short Companies House number
  app/forms/flood_risk_engine/company_number_form.rb
  spec/forms/flood_risk_engine/company_number_forms_spec.rb
Labels: bug

#433 Fix version page in production mode
  app/presenters/flood_risk_engine/application_version_page_presenter.rb
  app/views/pages/version.html.erb
  spec/presenters/flood_risk_engine/application_version_page_presenter_spec.rb
Labels: bug

#434 Fix links to OS Places terms
  app/views/flood_risk_engine/shared/_os_terms_footer.html.erb
  app/views/flood_risk_engine/shared/_postcode.html.erb
  app/views/pages/os_places_terms.html.erb
Labels: bug

#435 Validate company number with Companies House
  .github/workflows/ci.yml
  app/forms/flood_risk_engine/company_number_form.rb
  app/validators/ea/validators/companies_house_name_validator.rb
  app/validators/ea/validators/companies_house_number_validator.rb
  app/validators/flood_risk_engine/company_number_validator.rb
  config/locales/flood_risk_engine/company_number_forms.en.yml
  lib/flood_risk_engine/configuration.rb
  spec/cassettes/companies_house_lookup_valid.yml
  spec/dummy/config/initializers/flood_risk_engine.rb
  spec/forms/flood_risk_engine/company_number_forms_spec.rb
  spec/requests/flood_risk_engine/company_number_forms_spec.rb
  spec/support/shared_examples/validators/validate_company_number.rb
  spec/validators/companies_house_name_validator_spec.rb
  spec/validators/companies_house_number_validator_spec.rb
Labels: enhancement

#436 Remove gem: jquery-rails
  Gemfile.lock
  flood_risk_engine.gemspec
  spec/dummy/app/assets/javascripts/application.js
  spec/dummy/config/application.rb
Labels: dependencies

#437 Styling: Error pages
  app/views/flood_risk_engine/errors/error_401.html.erb
  app/views/flood_risk_engine/errors/error_403.html.erb
  app/views/flood_risk_engine/errors/error_404.html.erb
  app/views/flood_risk_engine/errors/error_422.html.erb
  app/views/flood_risk_engine/errors/error_generic.html.erb
  app/views/flood_risk_engine/errors/error_step_not_valid.html.erb
  config/locales/flood_risk_engine/errors.en.yml
Labels: enhancement

#438 Upgrade to Rails 6.1
  Gemfile.lock
  app/mailers/flood_risk_engine/application_mailer.rb
  app/models/flood_risk_engine/transient_address.rb
  flood_risk_engine.gemspec
  spec/dummy/config/environments/development.rb
  spec/dummy/config/environments/test.rb
  spec/validators/grid_reference_validator_spec.rb
Labels: dependencies

#440 Remove gem: has_secure_token
  Gemfile.lock
  app/models/flood_risk_engine/address.rb
  app/models/flood_risk_engine/enrollment.rb
  app/models/flood_risk_engine/transient_registration.rb
  flood_risk_engine.gemspec
  lib/flood_risk_engine/engine.rb
Labels: bug

#441 Set assistance mode when completing registration
  app/services/flood_risk_engine/registration_completion_service.rb
  lib/flood_risk_engine/configuration.rb
  spec/dummy/config/initializers/flood_risk_engine.rb
  spec/services/flood_risk_engine/registration_completion_service_spec.rb
Labels: enhancement

#443 Restore gem: jquery-rails
  Gemfile.lock
  flood_risk_engine.gemspec
  spec/dummy/app/assets/javascripts/application.js
  spec/dummy/config/application.rb
Labels: dependencies
