Repository DEFRA/flood-risk-engine, pull requests merged in 2021-11, with the labels that each got.

#448 Add timestamps to transient records
  db/migrate/20210621101800_create_transient_registrations.rb
  db/migrate/20210629070929_create_transient_addresses.rb
  db/migrate/20210629071403_create_transient_people.rb
  db/migrate/20210629072138_create_transient_registration_exemptions.rb
  spec/dummy/db/schema.rb
Labels: bug

#449 Update NCCC contact email address
  config/locales/flood_risk_engine/enrollment_mailer.en.yml
Labels: enhancement

#454 Bump dependencies
  Gemfile.lock
  flood_risk_engine.gemspec
Labels: dependencies
