Repository DEFRA/flood-risk-engine, pull requests merged in 2021-06, with the labels that each got.

#379 PECR Audit - Action 5 - update cookies page
  app/views/pages/cookies.html.erb
  config/locales/pages/cookies.en.yml
Labels: enhancement

#378 Switch to defra-ruby-address gem for address lookups
  .github/workflows/ci.yml
  Gemfile.lock
  app/forms/flood_risk_engine/steps/base_address_form.rb
  app/forms/flood_risk_engine/steps/base_address_search_form.rb
  app/services/flood_risk_engine/address_lookup_service.rb
  app/services/flood_risk_engine/address_services/deserialize/ea_facade_to_address.rb
  app/services/flood_risk_engine/address_services/find_by_postcode.rb
  app/services/flood_risk_engine/address_services/find_by_uprn.rb
  app/services/flood_risk_engine/address_services/search_service_failure.rb
  app/services/flood_risk_engine/base_service.rb
  app/views/flood_risk_engine/shared/_address.html.erb
  config/initializers/address_lookup.rb
  config/initializers/defra_ruby_address.rb
  flood_risk_engine.gemspec
  lib/flood_risk_engine/engine.rb
  spec/cassettes/address_lookup_no_matches_postcode.yml
  spec/cassettes/address_lookup_valid_postcode.yml
  spec/cassettes/forms_address_form_no_street_from_dropdown.yml
  spec/cassettes/forms_address_form_valid_uprn_from_dropdown.yml
  spec/controllers/flood_risk_engine/enrollments/steps_controller/addresses_spec.rb
  spec/controllers/flood_risk_engine/enrollments/steps_controller/postcodes_spec.rb
  spec/dummy/config/initializers/address_lookup.rb
  spec/factories/address_search_factory.rb
  spec/factories/enrollments_factory.rb
  spec/forms/flood_risk_engine/steps/individual_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/individual_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_company_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_company_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_liability_partnership_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_liability_partnership_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/local_authority_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/local_authority_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/other_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/other_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/partnership_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/partnership_postcode_form_spec.rb
  spec/rails_helper.rb
  spec/services/flood_risk_engine/address_lookup_service_spec.rb
  spec/support/vcr.rb
Labels: enhancement

#384 Return correct error for valid postcode without results
  app/forms/flood_risk_engine/steps/base_address_search_form.rb
  spec/cassettes/address_lookup_no_matches_postcode.yml
  spec/controllers/flood_risk_engine/enrollments/steps_controller/postcodes_spec.rb
  spec/forms/flood_risk_engine/steps/limited_company_postcode_form_spec.rb
Labels: bug

#383 Save blank instead of nil when populating address org
  app/forms/flood_risk_engine/steps/base_address_form.rb
  spec/cassettes/address_lookup_valid_postcode_no_organisation.yml
  spec/factories/page_related_enrollments_factory.rb
  spec/forms/flood_risk_engine/steps/limited_company_address_form_spec.rb
Labels: bug

#385 Clean up duplicate address after address is changed
  app/models/flood_risk_engine/address.rb
  spec/factories/enrollments_factory.rb
  spec/models/flood_risk_engine/address_spec.rb
Labels: bug

#386 Switch to defra-ruby-gem for address lookups
  .github/workflows/ci.yml
  Gemfile.lock
  app/forms/flood_risk_engine/steps/base_address_form.rb
  app/forms/flood_risk_engine/steps/base_address_search_form.rb
  app/models/flood_risk_engine/address.rb
  app/services/flood_risk_engine/address_lookup_service.rb
  app/services/flood_risk_engine/address_services/deserialize/ea_facade_to_address.rb
  app/services/flood_risk_engine/address_services/find_by_postcode.rb
  app/services/flood_risk_engine/address_services/find_by_uprn.rb
  app/services/flood_risk_engine/address_services/search_service_failure.rb
  app/services/flood_risk_engine/base_service.rb
  app/views/flood_risk_engine/shared/_address.html.erb
  config/initializers/address_lookup.rb
  config/initializers/defra_ruby_address.rb
  flood_risk_engine.gemspec
  lib/flood_risk_engine/engine.rb
  spec/cassettes/address_lookup_no_matches_postcode.yml
  spec/cassettes/address_lookup_valid_postcode.yml
  spec/cassettes/address_lookup_valid_postcode_no_organisation.yml
  spec/cassettes/forms_address_form_no_street_from_dropdown.yml
  spec/cassettes/forms_address_form_valid_uprn_from_dropdown.yml
  spec/cassettes/limited_company_postcode_address_service_400_test.yml
  spec/controllers/flood_risk_engine/enrollments/steps_controller/addresses_spec.rb
  spec/controllers/flood_risk_engine/enrollments/steps_controller/postcodes_spec.rb
  spec/dummy/config/initializers/address_lookup.rb
  spec/factories/address_search_factory.rb
  spec/factories/enrollments_factory.rb
  spec/factories/page_related_enrollments_factory.rb
  spec/forms/flood_risk_engine/steps/individual_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/individual_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_company_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_company_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_liability_partnership_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/limited_liability_partnership_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/local_authority_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/local_authority_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/other_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/other_postcode_form_spec.rb
  spec/forms/flood_risk_engine/steps/partnership_address_form_spec.rb
  spec/forms/flood_risk_engine/steps/partnership_postcode_form_spec.rb
  spec/models/flood_risk_engine/address_spec.rb
  spec/rails_helper.rb
  spec/services/flood_risk_engine/address_lookup_service_spec.rb
  spec/support/vcr.rb
Labels: enhancement

#387 Add error logging for address lookup service failures
  app/forms/flood_risk_engine/steps/base_address_search_form.rb
  spec/controllers/flood_risk_engine/enrollments/steps_controller/postcodes_spec.rb
Labels: housekeeping

#389 Add error logging for address lookup service failures
  app/forms/flood_risk_engine/steps/base_address_search_form.rb
  spec/controllers/flood_risk_engine/enrollments/steps_controller/postcodes_spec.rb
Labels: housekeeping

#390 Set up new registration workflow with AASM
  .rubocop.yml
  Gemfile.lock
  app/models/concerns/flood_risk_engine/.git-keep
  app/models/concerns/flood_risk_engine/can_have_registration_attributes.rb
  app/models/concerns/flood_risk_engine/can_use_new_registration_workflow.rb
  app/models/flood_risk_engine/new_registration.rb
  app/models/flood_risk_engine/transient_registration.rb
  db/migrate/20210621101800_create_transient_registrations.rb
  flood_risk_engine.gemspec
  lib/flood_risk_engine/engine.rb
  spec/dummy/db/schema.rb
  spec/factories/new_registrations_factory.rb
  spec/models/flood_risk_engine/new_registration_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/additional_contact_email_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/business_type_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/check_your_answers_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/company_address_lookup_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/company_address_manual_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/company_name_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/company_number_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/company_postcode_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/confirm_exemption_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/contact_email_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/contact_name_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/contact_phone_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/declaration_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/exemption_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/partner_address_lookup_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/partner_address_manual_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/partner_name_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/partner_overview_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/partner_postcode_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/registration_complete_form_spec.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/site_grid_reference_form.rb
  spec/models/flood_risk_engine/new_registration_workflow_state/start_form_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/helpers/workflow_states.rb
  spec/support/shared_examples/models/transient_registration.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_fixed_final_state.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_postcode_transition.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/an_address_lookup_transition.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/has_back_transition.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/has_next_transition.rb
Labels: enhancement
